services:
  app:
    container_name: ontwikkelstraat
    build: .
    image: foekinator656/dockerontwikkelstraat
    ports:
      - 4200:80
    networks:
      - ontwikkelstraatweb_front
    depends_on:
      - api
  api:
    image: foekinator656/dockerontwikkelstraat
    ports:
      - 8080:80
    networks:
      - ontwikkelstraatweb_front
      - ontwikkelstraatweb_back
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  db:
    image: "postgres:13.1-alpine"
    container_name: db
    ports:
      - 5432:80
    networks:
      - ontwikkelstraatweb_back
    environment:
      POSTGRES_DB: automatischefrituur
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: appeltaart
networks:
  ontwikkelstraatweb_front:
  ontwikkelstraatweb_back:
