#version: "3"
#services:
#  db:
#    image: "postgres"
#    container_name: db
#    environment:
#      POSTGRES_DB: automatischefrituur
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: appeltaart
#    ports:
#      - 5432:5432
#    networks:
#      - backdb
#
#  back:
#    build:
#      context: .
#    image: back
#    container_name: back
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    networks:
#      - backdb
#
#  front:
#    build: .
#    image: front
#    container_name: front
#    ports:
#      - 4200:4200
#    networks:
#      - backdb
#
#networks:
#  backdb:

version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: automatischefrituur
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: appeltaart
    ports:
      - 5432:5432
    networks:
      - backdb
    expose:
      - 5432

  back:
    build:
      context: ISENSIOT_backendV2
      dockerfile: Dockerfile-backend
    image: backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backdb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: frontend
    container_name: frontend
    ports:
      - 4200:4200
    networks:
      - backdb

networks:
  backdb:
    driver: bridge
