# Stage 1: Build the application with Maven
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY ISENSIOT_backendV2/pom.xml .
COPY ISENSIOT_backendV2/src ./src
RUN mvn clean package -DskipTests --fail-never

# Stage 2: Create a minimal runtime image
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

#FROM node:lts-alpine
#WORKDIR /app
#COPY package*.json ./
#RUN npm install -g @angular/cli
#RUN npm install --force
#RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
#COPY . .
#RUN pwd
#RUN ls
#RUN npm run build
#FROM nginx:stable
## COPY default.conf /etc/nginx/conf.d
#COPY --from=build /app/dist/isensiot-front-end/browser/ /usr/share/nginx/html
